
    create table acesso (
        id bigint generated by default as identity,
        perfil varchar(255),
        primary key (id)
    );

    create table categoria_produto (
        id bigint generated by default as identity,
        nome_desc varchar(255) not null,
        primary key (id)
    );

    create table endereco (
        id bigint generated by default as identity,
        pessoa_id bigint,
        bairro varchar(255),
        cep varchar(255),
        cidade varchar(255),
        complemento varchar(255),
        numero varchar(255),
        rua_logra varchar(255),
        uf varchar(255),
        tipo_endereco enum ('COBRANCA','ENTREGA'),
        primary key (id)
    );

    create table marca_produto (
        id bigint generated by default as identity,
        nome_desc varchar(255) not null,
        primary key (id)
    );

    create table pessoa (
        id bigint generated by default as identity,
        email varchar(255),
        nome varchar(255),
        telefone varchar(255),
        primary key (id)
    );

    create table pessoa_fisica (
        data_nascimento date,
        pessoa_id bigint not null,
        cpf varchar(255),
        primary key (pessoa_id)
    );

    create table pessoa_juridica (
        id bigint not null,
        categoria varchar(255),
        cnpj varchar(255),
        insc_estadual varchar(255),
        insc_municipal varchar(255),
        nome_fantasia varchar(255),
        razao_social varchar(255),
        primary key (id)
    );

    create table usuario (
        data_atual_senha timestamp(6),
        id bigint generated by default as identity,
        login varchar(255) unique,
        senha varchar(255),
        primary key (id)
    );

    create table usuario_acesso (
        perfil_id bigint not null,
        usuario_id bigint not null,
        primary key (perfil_id, usuario_id)
    );

    alter table if exists endereco 
       add constraint FKn1l2g0b74rqd9ywu29sva9sy9 
       foreign key (pessoa_id) 
       references pessoa;

    alter table if exists pessoa_fisica 
       add constraint FKg68at8xrubho690mo11i8k02x 
       foreign key (pessoa_id) 
       references pessoa;

    alter table if exists pessoa_juridica 
       add constraint FKor0e1i8f3vc9f721q0wcx1nbp 
       foreign key (id) 
       references pessoa;

    alter table if exists usuario_acesso 
       add constraint FK679pr3fcd9ko1jgojjhk5a3id 
       foreign key (perfil_id) 
       references acesso;

    alter table if exists usuario_acesso 
       add constraint FK3enjoxhenfwfbv6vndhq2ijo7 
       foreign key (usuario_id) 
       references usuario;
